'''
This file has code to do diagnostics analysis for the catalogs generated by Astronomy GMM Source Finder (AGSF). 
Author: Syed Faisal ur Rahman
Version: 1.0
'''
import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Try importing scipy, handle gracefully if missing
try:
    from scipy.optimize import curve_fit
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False
    print("Warning: 'scipy' not found. Curve fitting lines will be skipped.")

# --- PUBLICATION STYLE ---
plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 12,
    'axes.linewidth': 1.5,
    'xtick.major.width': 1.5,
    'ytick.major.width': 1.5,
    'xtick.direction': 'in',
    'ytick.direction': 'in',
    'xtick.top': True,
    'ytick.right': True,
    'legend.frameon': False
})

class DiagnosticsRunner:
    def __init__(self, components_csv, islands_csv, output_dir):
        self.comp_csv = components_csv
        self.isl_csv = islands_csv
        self.out_dir = os.path.join(output_dir, 'diagnostics')
        
        if not os.path.exists(self.out_dir):
            os.makedirs(self.out_dir)
            
        self.df = pd.read_csv(self.comp_csv)
        self.df_isl = pd.read_csv(self.isl_csv)
        
        if 'SNR' not in self.df.columns:
            # Avoid divide by zero
            rms = self.df['RMS'].replace(0, 1e-9)
            self.df['SNR'] = self.df['Peak_flux'] / rms

    def run_all(self):
        print(f"--- Running Diagnostics on {len(self.df)} sources ---")
        self.plot_flux_ratio()
        self.plot_error_validation()
        self.plot_source_counts()
        self.plot_size_snr()
        print(f"Diagnostics saved to: {self.out_dir}")

    def plot_flux_ratio(self):
        df = self.df
        ratio = df['Total_flux'] / df['Peak_flux']
        snr = df['SNR']
        
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.scatter(snr, ratio, c='k', s=10, alpha=0.5, label='Sources')
        
        x = np.logspace(np.log10(max(0.1, snr.min())), np.log10(max(1, snr.max())), 100)
        # Fixed Raw String (r'') to solve SyntaxWarning
        upper = 1 + (2.5 / x)
        lower = 1 - (2.5 / x)
        
        ax.plot(x, upper, 'r--', label=r'Unresolved Envelope (2.5$\sigma$)')
        ax.plot(x, lower, 'r--')
        ax.axhline(1.0, color='gray', linestyle='-', alpha=0.5)
        
        ax.set_xscale('log')
        ax.set_ylim(0, 3)
        ax.set_xlabel('Signal-to-Noise Ratio (SNR)')
        ax.set_ylabel(r'Flux Ratio ($S_{int} / S_{peak}$)')
        ax.set_title('Metric 1: Resolved Source Check')
        ax.legend()
        
        plt.savefig(os.path.join(self.out_dir, "diag_flux_ratio.png"), dpi=300, bbox_inches='tight')
        plt.close()

    def plot_error_validation(self):
        df = self.df
        rel_err = df['E_Peak_flux'] / df['Peak_flux']
        snr = df['SNR']
        
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.scatter(snr, rel_err, c='dodgerblue', s=10, alpha=0.6, label='GMM Errors')
        
        x = np.linspace(snr.min(), snr.max(), 100)
        y = np.sqrt((1/x)**2 + (0.01)**2)
        
        ax.plot(x, y, 'r-', lw=2, label='Condon Theory')
        
        ax.set_xscale('log')
        ax.set_yscale('log')
        ax.set_xlabel('SNR')
        ax.set_ylabel(r'$\sigma_S / S$')
        ax.set_title('Metric 2: Error Robustness')
        ax.legend()
        
        plt.savefig(os.path.join(self.out_dir, "diag_errors.png"), dpi=300, bbox_inches='tight')
        plt.close()

    def plot_source_counts(self):
        fluxes = self.df['Total_flux']
        if len(fluxes) == 0: return

        bins = np.logspace(np.log10(max(1e-9, fluxes.min())), np.log10(fluxes.max()), 20)
        hist, edges = np.histogram(fluxes, bins=bins)
        centers = (edges[:-1] + edges[1:]) / 2
        dS = np.diff(edges)
        
        counts = hist / dS
        norm_counts = counts * (centers ** 2.5)
        
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.loglog(centers, norm_counts, 'o-', color='darkorange', lw=2)
        
        ax.set_xlabel('Flux Density S (Jy)')
        ax.set_ylabel(r'Normalized Counts $S^{2.5} \frac{dN}{dS}$')
        ax.set_title('Metric 3: Source Counts')
        ax.grid(True, which='both', alpha=0.2)
        
        plt.savefig(os.path.join(self.out_dir, "diag_counts.png"), dpi=300, bbox_inches='tight')
        plt.close()
        
    def plot_size_snr(self):
        df = self.df
        size = df['Maj']
        snr = df['SNR']
        
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.scatter(snr, size, c='seagreen', s=10, alpha=0.5)
        
        ax.set_xscale('log')
        ax.set_yscale('log')
        ax.set_xlabel('SNR')
        ax.set_ylabel('Major Axis (arcsec)')
        ax.set_title('Metric 4: Morphology vs SNR')
        
        plt.savefig(os.path.join(self.out_dir, "diag_sizes.png"), dpi=300, bbox_inches='tight')
        plt.close()